### ISSUE TITLE
Unable to add process to process monitor group

### ISSUE THREAD

**Issue by GokulNC** [Asaurus1/streamlit-process-manager#1]
Error:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/gokul/filename.py", line 81, in <module>
    pm.group("multi").add(my_process)
  File "/opt/conda/lib/python3.10/site-packages/streamlit_process_manager/group.py", line 43, in add
    return proxy.ProcessProxy(process, pgroup=self)
  File "/opt/conda/lib/python3.10/site-packages/streamlit_process_manager/proxy.py", line 36, in __init__
    self.supports_remove = self._pgroup_weak is not None
  File "/opt/conda/lib/python3.10/site-packages/streamlit_process_manager/proxy.py", line 219, in __setattr__
    raise AttributeError("supports_remove is read-only")
AttributeError: supports_remove is read-only
```

`my_process` was instantiated with `pm.single(spm.Process(command, output_file))`

**Comment by Asaurus1** [comment]
@GokulNC thanks! I think the error messaging needs to be improved here, so I will do that.

You've already added your process to the `ProcessManager` via the `pm.single()` function. `single` is just a special way of creating a `ProcessGroup` that can only ever contain _one_ `Process`.

In the current version, you cannot then add the _same process_ to another group via `pm.group()` function (you would need to create a second process and add it to the `"multi"` group).

So if your code looks something like this
```python
pm = spm.get_manager()
my_process = pm.single(spm.Process(command, output_file))
pm.group("multi").add(my_process)
```

perhaps it should be changed to
```python
pm = spm.get_manager()
my_process = pm.single(spm.Process(command, output_file), group="multi")
```
which will place the new process in the group named "multi".
